export const FETCH_PHOTOS = 'FETCH_PHOTOS';
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';
export const FETCH_PHOTOS_ERROR = 'FETCH_PHOTOS_ERROR';
export const SET_SELECTED_PHOTO = 'SET_SELECTED_PHOTO';